### ISSUE TITLE
How to start new game?

### ISSUE THREAD

**Issue by parkerlreed** [usineur/lugaru#1]
You click New User and it just does nothing. I think the PC version assumed you could type here. 

How can I get past this?

**Comment by usineur** [comment]
Use the right joystick to click on "New User". It should prompt a dialog box where you can enter your name.

**Comment by usineur** [comment]
It should prompt a dialog box when you click on "New user" with "A" button.

I don't know what can be wrong. Try to remove `Data/users` and/or `config.txt` in the lugaru directory.

**Comment by parkerlreed** [comment]
Yeah still nothing. Latest Atmosphere on 8.0.1. I did use the "Album" launch as I don't see another option for loading hbmenu. I did load it through hbmenu though.

**Comment by parkerlreed** [comment]
https://www.youtube.com/watch?v=XkqkKteYAQk

**Comment by usineur** [comment]
Mmh that's weird. I'm still on 7.0.1, no problem on my side.

I don't use hbmenu personally. Only hbloader. 

Btw, can you try this [nro](https://www.ferb.fr/switch/lugaru.nro) (just overwrite the old one) ?

**Comment by parkerlreed** [comment]
Does the same sound when I press A on New User but nothing pops up.

**Comment by usineur** [comment]
I just updated to Atmosphere 0.8.9. It works nice here.

I have no plan to update my Switch to 8.0.1 for now. Not sure if there is an impact with this ver.

Can you try to copy this [file](https://www.ferb.fr/switch/users) in the `Data` folder ?

Do you have access to the user "Tuner" with it ? Can you play with it ?

**Comment by parkerlreed** [comment]
Yep starts up fine at that point. Thanks!

**Comment by usineur** [comment]
Well, I don't know what happen on your side. It seems that SwkbdConfig failed in some way.

While I can't reproduce it myself, I will watch if some related issue is reported one day, for libnx or atmosphere

**Comment by parkerlreed** [comment]
I know what it was. I finally realized the hold R and full title trick. Comes up at that point. One thing I run into now is it just sits on loading the tutorial. 

I'm using the Homebrew Store version if that differs.

**Comment by parkerlreed** [comment]
And reextarcted from GitHub zip. Finally everything is good! Sorry for the bother.

**Comment by usineur** [comment]
No problem. At last, everything is fine.
